### PR TITLE
BookStore: Milestone5

### PR DESCRIPTION
**Pull request by brugobi**
### Styling

- We add style using CSS and Bulma;

### Thank you for the review

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @brugobi and @oloomoses, congratulations on this milestone :smile: The README and the commit messages are professional :fireworks: As well as the PR :1st_place_medal: There are a few comments we need to address before proceeding. Let us check the comments below:

- `Nav` - Let us kindly implement a drop-down list for the categories, currently, I cannot select any category in the nav. The filter category should be in the nav, it is currently not there. Let us kindly fix it
- Let us kindly use this screenshot as a guide in implementing our specified design
testt
The position of the remove button is not at the right place, there is no progress circle in our app, the current chapter and update progress should be added as in the design
- Let us keep our code DRY, currently, there are repeating attribute-value selectors. Let us improve our CSS file. For example; `font-family: "Montserrat", sans-serif;` appears more than 4 times

Once these are resolved, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by brugobi** [comment]
## Update the style

- we add the progress bar and the chapter section
- the filter is not inside the navbar (Navbar is just the template), it is under and working fine;

### Thank you for the review

**Review by trekab — CHANGES_REQUESTED** [review]
#### Changes Required! :recycle: 
Hi team! Well done working on the progress bar as requested by the last reviewer. There are some details from the last review I think you have still not implemented. These include:

- [x] Your project lacks the `UPDATE PROGRESS` button. You seem to have replaced it with `REMOVE` which is supposed to be between the `Comments` and `Edit` links just below the book title.
- [x] The filter should be in the page header replacing the `CATEGORIES` place holder.
- [ ] __[Optional]__ Your page appears to be filling almost the whole viewport width yet in the design it appears to be centered with some margin to the left and right.
- [ ] __[Optional]__ Add the book author just below the book title like in the design specification.

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Review by teekaytech — APPROVED** [review]
# Status: Approved :green_circle: 

### Congratulations team :tada: :clinking_glasses: 

**This project has passed all the mandatory requirements :clap: 
It is therefore approved :heavy_check_mark:**

**Comment(s)**
- You might want to consider implementing the optional changes recommended by the last reviewer. 

Again, congratulations, you can merge to the default branch.
Do not forget to fill the project completion form, as this is important for your weekly progress score.

**_Good luck with your next task._**

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Pull request merged**
